# -*- coding: utf-8 -*-
"""Reading, writing and normalising ``config.ini``.

The parsed config is a :class:`DotDict` so that ``cfg.GRID_SIZE`` and
``cfg['GRID_SIZE']`` are the same thing and a missing key reads as
``None`` rather than raising — the original program relies on both.

SPDX-License-Identifier: GPL-2.0-or-later
"""
from __future__ import annotations

import configparser
import os
import pickle
from io import StringIO
from typing import Any, Dict, Optional, Tuple

from . import runtime
from .configdefaults import CONFIGFILE_DEFAULT_CONTENTS
from .constants import CLINICAL_MODE, CONFIG_OVERWRITE_IF_OLDER_THAN
from .paths import get_data_dir, quit_with_error
from .i18n import _


class DotDict(Dict[str, Any]):
    """A dict whose keys are also attributes; unknown keys read as None."""

    def __getattr__(self, attr: str) -> Any:
        return self.get(attr, None)

    __setattr__ = dict.__setitem__  # type: ignore[assignment]
    __delattr__ = dict.__delitem__  # type: ignore[assignment]


def load_last_user(lastuserpath: str) -> None:
    """Restore the profile saved by :func:`save_last_user`, if any."""
    path = os.path.join(get_data_dir(), lastuserpath)
    if not os.path.isfile(path):
        return
    runtime.debug_msg("Trying to load '%s'" % path)
    try:
        with open(path, 'rb') as handle:
            options = pickle.Unpickler(handle).load()
    except Exception as exc:
        print("%s\nDue to error, continuing as user 'default'" % exc)
        # The pickle could not be loaded, so it is of no further use.
        os.remove(path)
        return
    user = options.get('USER', '')
    if user == '':
        print('Last loaded user is an empty string! '
              'Setting it to default instead')
        user = 'default'
    if user.lower() != 'default':
        runtime.set_user_files(user)


def save_last_user(lastuserpath: str) -> None:
    """Remember the active profile for the next launch."""
    try:
        with open(os.path.join(get_data_dir(), lastuserpath), 'wb') as handle:
            pickle.Pickler(handle).dump({'USER': runtime.USER})
    except Exception as exc:
        runtime.error_msg('Could not save last user', exc)


def _try_eval(text: str) -> Any:
    """Config values are Python literals where possible, else plain text."""
    try:
        return eval(text)
    except Exception:
        return text


def _upgrade_stale_config(fullpath: str, configpath: str) -> None:
    """Back up and regenerate a config written by an older version."""
    with open(fullpath, 'r+') as handle:
        while True:
            line = handle.readline()
            if line == '':
                # EOF: 'generated by Brain Workshop' never appeared.
                handle.close()
                rewrite_configfile(configpath, overwrite=True)
                return
            if line.find('generated by Brain Workshop') > -1:
                version = line.split()[5]
                if version < CONFIG_OVERWRITE_IF_OLDER_THAN:
                    handle.close()
                    os.rename(fullpath, '%s.%s.bak' % (fullpath, version))
                    rewrite_configfile(configpath, overwrite=True)
                return


def _clamp_grid_settings(cfg: DotDict) -> None:
    """Keep GRID_SIZE inside [GRID_SIZE_MIN, GRID_SIZE_MAX]."""
    try:
        gmin = int(cfg.GRID_SIZE_MIN) if cfg.GRID_SIZE_MIN is not None else 2
        gmax = int(cfg.GRID_SIZE_MAX) if cfg.GRID_SIZE_MAX is not None else 32
        gmin = max(2, gmin)
        gmax = max(gmin, gmax)
        cfg.GRID_SIZE_MIN = gmin
        cfg.GRID_SIZE_MAX = gmax
        cfg.GRID_SIZE = max(gmin, min(gmax, int(cfg.GRID_SIZE)))
    except Exception:
        cfg.GRID_SIZE = 3
        cfg.GRID_SIZE_MIN = 2
        cfg.GRID_SIZE_MAX = 32
    if cfg.GRID_INCLUDE_CENTER is None:
        cfg.GRID_INCLUDE_CENTER = False


def parse_config(configpath: str) -> DotDict:
    """Load *configpath*, layered on top of the built-in defaults."""
    user_config: Optional[configparser.ConfigParser] = None
    if not (CLINICAL_MODE and configpath == 'config.ini'):
        fullpath = os.path.join(get_data_dir(), configpath)
        if not os.path.isfile(fullpath):
            rewrite_configfile(configpath, overwrite=False)
        _upgrade_stale_config(fullpath, configpath)
        try:
            user_config = configparser.ConfigParser()
            user_config.read(fullpath)
        except Exception as exc:
            runtime.debug_msg(exc)
            user_config = None
            if configpath != 'config.ini':
                quit_with_error(_('Unable to load config file: %s') % fullpath)

    default_config = configparser.ConfigParser()
    default_config.read_file(StringIO(CONFIGFILE_DEFAULT_CONTENTS))

    configs: Tuple[configparser.ConfigParser, ...]
    if user_config is None:
        configs = (default_config,)
    else:
        # Defaults first, so an incomplete user config still resolves.
        configs = (default_config, user_config)

    cfg = DotDict()
    for config in configs:
        cfg.update([(k.upper(), _try_eval(v))
                    for k, v in config.items('DEFAULT')])

    if 'CHANCE_OF_INTERFERENCE' not in cfg:
        cfg.CHANCE_OF_INTERFERENCE = cfg.DEFAULT_CHANCE_OF_INTERFERENCE
    _clamp_grid_settings(cfg)

    statsfile = runtime.get_argv('--statsfile')
    if statsfile:
        cfg.STATSFILE = statsfile
    return cfg


def rewrite_configfile(configfile: str, overwrite: bool = False) -> None:
    """Create *configfile* (and its stats files) if missing or stale."""
    if runtime.USER.lower() == 'default':
        statsfile = 'stats.txt'
        # Command-line options may still point at non-default files.
        runtime.STATS_BINARY = 'logfile.dat'
    else:
        statsfile = runtime.USER + '-stats.txt'

    data_dir = get_data_dir()
    try:
        os.stat(os.path.join(data_dir, configfile))
    except OSError as exc:
        runtime.debug_msg(exc)
        overwrite = True
    if overwrite:
        with open(os.path.join(data_dir, configfile), 'w') as handle:
            handle.write(CONFIGFILE_DEFAULT_CONTENTS.replace(
                'stats.txt', statsfile))

    # Let us hope nobody uses '-stats.txt' in their user name.
    runtime.STATS_BINARY = statsfile.replace('-stats.txt', '-logfile.dat')
    for name in (statsfile, runtime.STATS_BINARY):
        try:
            os.stat(os.path.join(data_dir, name))
        except OSError as exc:
            runtime.debug_msg(exc)
            with open(os.path.join(data_dir, name), 'w'):
                pass


def _apply_environment_overrides(cfg: DotDict) -> None:
    """Let the CLI and environment win over the config file."""
    trials = os.environ.get('BRAINWORKSHOP_TRIALS')
    if trials is not None:
        count = int(trials)
        if count < 1:
            raise ValueError('BRAINWORKSHOP_TRIALS must be positive')
        # Make the requested session length exact at every n-back level.
        cfg.NUM_TRIALS = count
        cfg.NUM_TRIALS_FACTOR = 0

    if runtime.env_flag('BRAINWORKSHOP_MUTE_MUSIC'):
        cfg.USE_MUSIC = False

    for key, flag, env in (('TRIAL_INTERVAL_MS', '--trial-ms', 'NW_TRIAL_MS'),
                           ('TICK_DURATION_MS', '--tick-ms', 'NW_TICK_MS'),
                           ('STIMULUS_DURATION_MS', '--stim-ms', 'NW_STIM_MS')):
        value = runtime.get_argv(flag) or os.environ.get(env)
        if value is not None:
            cfg[key] = int(value)


def _apply_headless_defaults(cfg: DotDict) -> None:
    """Strip anything that would slow down or block an agent run."""
    if not (runtime.HEADLESS or cfg.HEADLESS):
        return
    runtime.HEADLESS = True
    cfg.HEADLESS = True
    cfg.SKIP_TITLE_SCREEN = True
    cfg.USE_MUSIC = False
    cfg.USE_APPLAUSE = False
    if not cfg.TRIAL_INTERVAL_MS:
        # Fast default for agent loops unless the user picked an interval.
        if not cfg.TICK_DURATION_MS or int(cfg.TICK_DURATION_MS) >= 100:
            cfg.TICK_DURATION_MS = 1
        cfg.TRIAL_INTERVAL_MS = max(10, int(cfg.TICK_DURATION_MS) * 10)


def _clamp_durations(cfg: DotDict) -> None:
    """Every millisecond duration must be a positive int."""
    for key, fallback in (('TICK_DURATION_MS', 100),
                          ('STIMULUS_DURATION_MS', 500),
                          ('FEEDBACK_DURATION_MS', 200)):
        try:
            cfg[key] = max(1, int(cfg[key] or fallback))
        except Exception:
            cfg[key] = fallback
    runtime.TICK_DURATION = cfg.TICK_DURATION_MS / 1000.0


def _apply_jaeggi_profile(cfg: DotDict) -> None:
    """Force the interface options the Jaeggi protocol prescribes."""
    if CLINICAL_MODE:
        cfg.JAEGGI_INTERFACE_DEFAULT_SCORING = False
        cfg.JAEGGI_MODE = True
        cfg.JAEGGI_FORCE_OPTIONS = True
        cfg.JAEGGI_FORCE_OPTIONS_ADDITIONAL = True
        cfg.SKIP_TITLE_SCREEN = True
        cfg.USE_MUSIC = False
    elif cfg.JAEGGI_INTERFACE_DEFAULT_SCORING:
        cfg.ANIMATE_SQUARES = False
        cfg.OLD_STYLE_SQUARES = True
        cfg.OLD_STYLE_SHARP_CORNERS = True
        cfg.GRIDLINES = False
        cfg.CROSSHAIRS = True
        cfg.SHOW_FEEDBACK = False
        cfg.BLACK_BACKGROUND = True
        cfg.WINDOW_FULLSCREEN = True
        cfg.HIDE_TEXT = True
        cfg.FIELD_EXPAND = True

    if cfg.JAEGGI_MODE and not cfg.JAEGGI_INTERFACE_DEFAULT_SCORING:
        cfg.GAME_MODE = 2
        cfg.VARIABLE_NBACK = 0
        cfg.JAEGGI_SCORING = True
        if cfg.JAEGGI_FORCE_OPTIONS:
            cfg.AUDIO1_SETS = ['letters']
            cfg.ANIMATE_SQUARES = False
            cfg.OLD_STYLE_SQUARES = True
            cfg.OLD_STYLE_SHARP_CORNERS = True
            cfg.GRIDLINES = False
            cfg.CROSSHAIRS = True
            cfg.SHOW_FEEDBACK = False
            cfg.THRESHOLD_FALLBACK_SESSIONS = 1
            cfg.NUM_TRIALS_FACTOR = 1
            cfg.NUM_TRIALS_EXPONENT = 1
        if cfg.JAEGGI_FORCE_OPTIONS_ADDITIONAL:
            cfg.BLACK_BACKGROUND = True
            cfg.WINDOW_FULLSCREEN = True
            cfg.HIDE_TEXT = True
            cfg.FIELD_EXPAND = True

    if not cfg.USE_SESSION_FEEDBACK:
        cfg.USE_MUSIC = False
        cfg.USE_APPLAUSE = False

    if cfg.BLACK_BACKGROUND:
        cfg.COLOR_TEXT = cfg.COLOR_TEXT_BLK


def load_configuration() -> DotDict:
    """Parse the active user's config and normalise it for this run."""
    cfg = parse_config(runtime.CONFIGFILE)
    _apply_environment_overrides(cfg)
    _apply_headless_defaults(cfg)
    _clamp_durations(cfg)
    _apply_jaeggi_profile(cfg)
    return cfg


def get_threshold_advance() -> float:
    """Score at or above which the n-back level goes up."""
    from . import state
    cfg = state.cfg
    return cfg.JAEGGI_ADVANCE if cfg.JAEGGI_SCORING else cfg.THRESHOLD_ADVANCE


def get_threshold_fallback() -> float:
    """Score below which the n-back level drops back down."""
    from . import state
    cfg = state.cfg
    return cfg.JAEGGI_FALLBACK if cfg.JAEGGI_SCORING else cfg.THRESHOLD_FALLBACK
